### PR TITLE
Fixed compilation with GHC 7.10.1.RC3

### PR DESCRIPTION
**Pull request by asr**

### CODE REVIEW

**Comment by doaitse** [comment]
Thanks. I am on vacation but will forward your message to atzeDijkstra,

 Doaitse

**Comment by phile314** [comment]
I will take care of this and discuss this with Atze as needed.

Philipp

**Comment by phile314** [comment]
@atzedijkstra If somebody adds me to the hackage maintainers for uulib, I can upload the new version for GHC 7.10 later. My hackage user name is PhilippHausmann .

**Comment by uhc** [comment]
I have added you to the hackage maintainers. Do you also verify that these patches work with ghc 7.8.x?

A

> On  26 Mar, 2015, at 14:36 , Philipp Hausmann notifications@github.com wrote:
> 
> @atzedijkstra If somebody adds me to the hackage maintainers for uulib, I can upload the new version for GHC 7.10 later. My hackage user name is PhilippHausmann .
> 
> —
> Reply to this email directly or view it on GitHub.

```
            - Atze -
```

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by phile314** [comment]
Yes, I checked the patches with GHC 7.8.x. I haven't done a full UHC build with the patched package yet, but I will do that before releasing it.

**Pull request merged**
